# LAB 01 - Submission example

In [1]:
#!wget -nc --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/20201.test/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

In [ ]:
from local.lib.rlxmoocapi import submit, session
import inspect
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

-----------
you are raul.ramos@udea.edu.co .... wait for the cell below to complete signup
-----------

In [3]:
student = session.Session(init.endpoint).login(course_id=init.course_id, lab_id='L01.01', google_token=google_token)

using course session 20201.test::YYYY
success!! you are logged in


In [4]:
import numpy as np

## Ejercicio 1: Obtén el máximo y el mínimo de una lista

Una de las estructuras de datos en python son las listas, y aprender a obtener datos de ellas es importante para el manejo del lenguaje, por esto vamos a hallar el **max** y el **min** de una de ellas

Ejemplo:
    [1, 7, 11, 3, 5, 2]
    
    el minimo valor es 1
    el valor maximo es 11
    
Deberás de calcular el máximo y mínimo de la siguiente lista. Puedes obtenerlos como quieras (a mano, programando en python, con excel, etc.).    

In [5]:
lst = np.random.randint(50, size=20)
lst

array([42,  9, 20, 43, 38, 17, 27,  0, 31,  9, 34, 15, 17,  9,  5, 37, 16,
       44, 47, 33])

**Tu solución**

Debes de asignar a las variables max y min el valor del maximo y minimo valor en la lista list

In [ ]:
maximum = ...
minimum = ...

In [6]:
## TEACHER
maximum = np.max(lst)
minimum = np.min(lst)
maximum, minimum

(47, 0)

In [ ]:
## TEACHER
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="teacher");

-----------
you are raul.ramos@udea.edu.co .... wait for the cell below to complete signup
-----------

In [8]:
teacher = session.Session(init.endpoint).login(course_id=init.course_id, lab_id='L01.01', google_token=google_token)

using course session 20201.test::YYYY
success!! you are logged in


In [9]:
## TEACHER DEFINEGRADER
def grader_01(functions, variables, caller_userid):
    import numpy as np
    
    st_list = variables['lst']
    st_max = variables['maximum']
    st_min = variables['minimum']
    t_max = np.max(st_list)
    t_min = np.min(st_list)
        
    if (t_max==st_max) & (t_min==st_min):
        return 5, '<b>correct</b>'
    else:
        return 0, '<b>incorrect</b>'
    
source_functions_names_01 = []
source_variables_names_01 = ['lst', 'maximum', 'minimum']

In [10]:
## TEACHER
teacher.run_grader_locally("grader_01", source_functions_names_01, source_variables_names_01, locals())

In [11]:
## TEACHER SETGRADER
import inspect
teacher.set_grader(init.course_id, "L01.01", 'T01',
                  inspect.getsource(grader_01), 'grader_01',
                  source_functions_names_01, source_variables_names_01)

**Registra tu solución en linea**

In [12]:
student.submit_task(namespace=globals(), task_id='T01');

## Ejercicio 2: Crea dos funciones que encuentren la media y desviación estándar

Completa las dos funciones `list_mean` y `list_std` para que al recibir una lista o un vector `numpy` como argumento calculen la media y desviación estándar, respectivamente.

Ejemplo:

    > lst_1 = np.random.randint(10, size=5)
    > print(lst_1)
    > print(list_mean(lst_1))
    > print(list_stdev(lst_1))
    
    [6 4 1 7 2]
    4.0
    2.280350850198276
    

In [13]:
import numpy as np

def list_mean(lst):
    ## your code here ##
    mean = ...
    return mean

def list_stdev(lst):
    ## your code here ##
    stdev = ...
    return stdev

In [14]:
## TEACHER
import numpy as np

def list_mean(lst):
    ## your code here ##
    mean = np.mean(lst)
    return mean

def list_stdev(lst):
    ## your code here ##
    stdev = np.std(lst)
    return stdev

Prueba tus funciones

In [15]:
lst_1 = np.random.randint(10, size=5)
print(lst_1)
print(list_mean(lst_1))
print(list_stdev(lst_1))

[5 8 1 3 6]
4.6
2.4166091947189146


In [16]:
## TEACHER DEFINEGRADER
def grader_02(functions, variables, caller_userid):
    import numpy as np
        
    # retrieve definitions
    namespace = locals()
    for f in functions.values():
        exec(f, namespace)

    st_mean_funct = namespace['list_mean']
    st_stdev_funct = namespace['list_stdev']
    
    error = False
    msg = ''
    
    for i in range(100):
        size = np.random.randint(20)+3
        list = np.random.randint(10, size=size)
        mean = np.mean(list)
        stdev = np.std(list)
        if not (mean==st_mean_funct(list)):
            msg += "input\nlist = \n%s\n"%(str(list))
            msg += "expected output:%s\n"%str(mean)
            msg += "output obtained:%s\n"%str(st_mean_funct(list))
            error = True
            break
        if not (stdev==st_stdev_funct(list)):
            msg += "input\nlist = \n%s\n"%(str(list))
            msg += "expected output:%s\n"%str(stdev)
            msg += "output obtained:%s\n"%str(st_stdev_funct(list))
            error = True
            break
    
    if not error:
        msg += u'<b>CORRECT</b>'
        return 5, '<b>correct</b>'
    else:
        msg += u'<b><font color="red">INCORRECT</font></b>'
        return 0, msg
    
source_functions_names_02 = ['list_mean', 'list_stdev']
source_variables_names_02 = []

In [17]:
## TEACHER
teacher.run_grader_locally("grader_02", source_functions_names_02, source_variables_names_02, locals())

In [18]:
## TEACHER SETGRADER
teacher.set_grader(init.course_id, "L01.01", 'T02',
                  inspect.getsource(grader_02), 'grader_02',
                  source_functions_names_02, source_variables_names_02)

**Registra tu solución en linea**

In [19]:
student.submit_task(namespace=globals(), task_id='T02');

In [20]:
## TEACHER
# --- CREATE or OVERWRITE STUDENTS NOTEBOOK --- 
#
# you MUST run the notebook server with no password or token with the following command line
#
#     jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''
#
# ---------------------------------------------- 
import init
from local.lib.rlxmoocapi import utils
student_notebook_fname = utils.convert_this_notebook_to_student()

<IPython.core.display.Javascript object>

NOTEBOOK name is LAB 01 - SUBMISSION EXAMPLE--XX--TEACHER--XX.ipynb
student notebook writen to 'LAB 01 - SUBMISSION EXAMPLE.ipynb'
